
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

recorder: !include recorder.yaml
automation: !include_dir_merge_list automations/
sensor: !include_dir_merge_list sensors/
script: !include_dir_merge_named scripts/
scene: !include scenes.yaml
light: !include lights.yaml
cover: !include covers.yaml
binary_sensor: !include binary_sensors.yaml
input_boolean: !include input_booleans.yaml
input_select: !include input_selects.yaml
input_number: !include input_numbers.yaml
utility_meter: !include utility_meters.yaml
group: !include groups.yaml

input_datetime:
  last_irrigation:
    has_date: true
    has_time: true

mqtt:
  light: !include_dir_merge_list mqtt/light/
  cover: !include_dir_merge_list mqtt/cover/
  switch: !include_dir_merge_list mqtt/switch/
  sensor: !include_dir_merge_list mqtt/sensor/

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.3

api:

alexa:
  smart_home:
