- platform: command_line
  name: DB size
  command: "ls -l /config/home-assistant_v2.db |  tr -s ' ' | cut -d' ' -f5"
  unit_of_measurement: "M"
  value_template: '{{ ((value | int) / 1024 / 1024) | int }}'

- platform: sql
  db_url: !secret mariadb_url
  queries:
    - name: MariaDB Size
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1048576, 2) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
      column: 'value'
      unit_of_measurement: MB

- platform: influxdb
  host: 192.168.1.12
  port: 8086
  username: homeassistant
  password: !secret influxdb_pass
  scan_interval: 3600
  queries:
    - name: InfluxDB Database Size
      unit_of_measurement: MB
      value_template: "{{ (value | float(0) / 1024 /1024) | round(1) }}"
      group_function: sum
      measurement: '"monitor"."shard"'
      database: _internal
      where: '"database"=''homeassistant'' AND time > now() - 5m'
      field: diskBytes

- platform: command_line
  name: Git alarm
  command: "[ $(git status -s | wc -l) -gt 0 ] && echo on || echo off"

- platform: systemmonitor
  resources:
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: disk_use_percent
    - type: memory_use_percent
    - type: memory_free
    - type: processor_use
    - type: processor_temperature
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: throughput_network_in
      arg: eth0
    - type: throughput_network_out
      arg: eth0
    - type: last_boot

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'
    - 'time_utc'