- platform: command_line
  name: DB size
  command: "ls -l /config/home-assistant_v2.db |  tr -s ' ' | cut -d' ' -f5"
  unit_of_measurement: "M"
  value_template: '{{ ((value | int) / 1024 / 1024) | int }}'

# Definizione del sensore sostituita configurando l'opportuna integrazione "SQL"
#- platform: sql
#  db_url: !secret mariadb_url
#  queries:
#    - name: MariaDB Size
#      query: "SELECT table_schema AS 'db_name', ROUND(SUM( data_length + index_length ) / 1024 / 1024, 2) AS 'size_mb' FROM information_schema.TABLES WHERE table_schema='homeassistant'"
#      column: 'size_mb'
#      unit_of_measurement: MB

- platform: command_line
  name: CPU temperature
  command: >
    read -r val </sys/class/thermal/thermal_zone1/temp;echo ${val}
  value_template: >
    {{value|multiply(0.001)|round(1)}}
  unit_of_measurement: °C

- platform: command_line
  name: Git alarm
  command: "[ $(git status -s | wc -l) -gt 0 ] && echo on || echo off"

- platform: systemmonitor
  resources:
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: disk_use_percent
    - type: memory_use_percent
    - type: memory_free
    - type: processor_use
#    - type: processor_temperature
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: throughput_network_in
      arg: eth0
    - type: throughput_network_out
      arg: eth0
    - type: last_boot

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'
    - 'time_utc'